In [46]:
%pylab
import pandas as pd
import itertools

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [47]:
A=[];B=[];t=[];
for i in arange(0,20):
    dataset=pd.read_table("./data/dataset_"+str(i)+".txt",header=None,names=["A","B","t"])
    t+=[array(dataset["t"])]
    A+=[array(dataset["A"])]
    B+=[array(dataset["B"])]

In [210]:
shape(array(t))

(20,)

In [48]:
figure(figsize=(4,3))
for i in arange(0,shape(t)[0]):
    #plot(t[i],A[i],"r",label="A")
    plot(t[i],B[i])
#legend()
#figure()
#plot(t, A+B)

In [49]:
m=min(t[0])
M=max(t[0])
for i in arange(0,shape(t)[0]):
    m_temp=min(t[i])
    if m>m_temp:
        m=m_temp
    M_temp=max(t[i])
    if M<M_temp:
        M=M_temp
# m minimum, M maximum time where something happen
t_bin=logspace(log10(m),log10(M),50);
    
    

In [25]:
h,b=histogram(t[0],t_bin,weights=A[0],normed=True)
cumsum(h)*diff(b)

array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   1.23954737e-05,
         1.60824424e-05,   4.08627409e-05,   1.01522200e-04,
         2.15141761e-04,   3.70280524e-04,   5.76502228e-04,
         7.83141234e-04,   1.05755524e-03,   1.42054724e-03,
         1.89893253e-03,   2.46376004e-03,   3.34937086e-03,
         4.34562365e-03,   5.81625523e-03,   7.54626984e-03,
         9.79086821e-03,   1.28327342e-02,   1.77709598e-02,
         2.37114491e-02,   3.09058488e-02,   4.13842363e-02,
         5.48851899e-02,   7.17257730e-02,   9.41298857e-02,
         1.27679614e-01,   1.69933723e-01,   2.34788890e-01,
         3.25843318e-01,   5.01417416e-01,   7.16255341e-01,
         1.01784607e+00,   1.44299602e+00,   2.16334705e+00,
         3.08696340e+00,   4.02626896e+00,   5.22386154e+00,
         6.77767175e+00]

I create the mean in the interbal by taking the weigthed average in the bin.  I sum all the weigths at the numerator and all the normalisation constant at the denominator. In the end then I divide the quantities.
The counts are computed through the function "fix_histogram" which takes 

In [50]:
def fix_histogram(h):
    for index in  where(h[1:]==0)[0]+1:
        h[index]=h[index-1]
    return h
def fix_histogram2(h):
    ch=cumsum(h)
    return ch -pad(ch,2,'constant',constant_values=(0))[:-4]

count=zeros(len(t_bin)-1)
count1=zeros(len(t_bin)-1)
for i in arange(0,len(t)):
    h,b=histogram(t[i],t_bin,weights=B[i])
    h1,b1=histogram(t[i],t_bin)
    count+=h
    count1+=h1
plot((b[1:]),fix_histogram(count)/fix_histogram(count1),"ro",label="average")
xlabel("t")
ylabel("B")
legend()
tight_layout()

In [85]:
count.shape

(999,)

In [46]:
print(h)
fix_histogram2(h)

[1180  755  507  268  222  192  117  102   56   31]


array([1180, 1935, 1262,  775,  490,  414,  309,  219,  158,   87])

In [30]:
figure()
h,b=histogram(t[0],10,weights=B[0])
h1,b1=histogram(t[0],10)
plot((b[:-1]+b[1:])/2.,fix_histogram(h)/fix_histogram(h1))
plot(t[0],B[0])
print(h,h1)
print(b)
print(t[0])


[772 681 846 357 369 302 266 149 159 160] [46 32 46 24 27 25 23 14 18 20]
[  7.98000000e-04   7.46567000e-01   1.49233600e+00   2.23810500e+00
   2.98387400e+00   3.72964300e+00   4.47541200e+00   5.22118100e+00
   5.96695000e+00   6.71271900e+00   7.45848800e+00]
[  7.98000000e-04   1.50300000e-03   1.96700000e-03   2.13200000e-03
   2.26100000e-03   2.58600000e-03   2.74400000e-03   3.15100000e-03
   3.45900000e-03   3.62000000e-03   4.03500000e-03   4.55100000e-03
   4.64700000e-03   5.73600000e-03   7.33600000e-03   8.38600000e-03
   1.16630000e-02   1.88620000e-02   1.90520000e-02   3.12960000e-02
   3.56860000e-02   6.47190000e-02   9.34720000e-02   9.35930000e-02
   9.51570000e-02   1.08259000e-01   1.13995000e-01   1.14198000e-01
   1.23381000e-01   1.68647000e-01   2.12494000e-01   2.23766000e-01
   2.30404000e-01   2.45016000e-01   2.53313000e-01   2.76104000e-01
   3.86356000e-01   4.01773000e-01   5.13257000e-01   5.80841000e-01
   5.97902000e-01   6.19276000e-01   6.208460

In [21]:
a=arange(0,10,1)
diff(a,2)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
x=arange(1,10)
s=cumsum(x)
print(x)
s-pad(s,2,'constant',constant_values=(0))[:-4]

[1 2 3 4 5 6 7 8 9]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [155]:
M-diff(t_bin)[0]

0.0085342500000000002

In [159]:
len(t_bin)

5

In [197]:
t[-1]

array([  3.59000000e-04,   6.48000000e-04,   1.52000000e-03,
         1.52300000e-03,   2.46300000e-03,   2.74400000e-03,
         3.36100000e-03,   3.76500000e-03,   4.30200000e-03,
         4.64400000e-03,   4.82900000e-03,   1.11380000e-02,
         1.14970000e-02,   1.44170000e-02,   1.64520000e-02,
         1.73090000e-02,   1.74230000e-02,   2.16650000e-02,
         2.46770000e-02,   2.72580000e-02,   2.77850000e-02,
         2.90160000e-02,   3.17970000e-02,   4.28410000e-02,
         6.01520000e-02,   1.17466000e-01,   1.70478000e-01,
         2.22733000e-01,   2.79903000e-01,   2.81825000e-01,
         2.97049000e-01,   3.67894000e-01,   3.84366000e-01,
         4.04891000e-01,   4.34229000e-01,   4.48632000e-01,
         4.48876000e-01,   4.61048000e-01,   4.66289000e-01,
         4.67149000e-01,   4.67796000e-01,   4.91212000e-01,
         5.39458000e-01,   6.00902000e-01,   6.03469000e-01,
         6.14851000e-01,   6.38293000e-01,   6.54595000e-01,
         6.57404000e-01,

In [195]:
shape(t[10])

(100,)